name: Exemplo de fluxo de trabalho 

on: 
    workflow_dispatch:
jobs:
    acao_inicial_job:
      runs-on: ubuntu-latest
      steps:
          - name: imprime Ola
            run: echo "Ola"
          - name: imprime TCHAU
            run: echo "Tchau"
    
    
